# Root
baseURL = 'https://clickinbad.arcade.aao.fyi/'
languageCode = 'en'
theme = 'gitlab.com/aao-fyi/shock'

# Info
title = 'ClickinBad'
copyright = 'ClickinBad Contributors'

# Features
disableHugoGeneratorInject = false
disableKinds = ['RSS','taxanomy','term']
enableGitInfo = true
enableRobotsTXT = true

# Minify
[minify]
  minifyOutput = true

# Build
[build]
  # PostCSS
  writeStats = true

# Module
[module]
  # Version
  [module.hugoVersion]
    extended = true
    min = '0.111.0'

[params]
  description = 'Click your life away in this Breaking Bad inspired clicker game.'
  # PostCSS
  postCSS = true
  # Bootstrap JS
  bootstrapJS = false
  # Navbar
  navbarBrandLogo = false
  navbarBrandText = false
  navbarFixedTop = false
  # Header
  headerState = false
  # Footer
  footerState = false
  # Manifest
  manifestJSON = true
  manifestColorBG = "#28d"


# Footer
[menu]
  [[menu.footer]]
    identifier = 'privacy'
    name = 'Privacy'
    url = 'https://aao.fyi/privacy/'
  [[menu.footer]]
    identifier = 'sitemap'
    name = 'Sitemap'
    url = '/sitemap.xml'
